---
- name: create vpc
  ec2_vpc_net:
    state: present
    cidr_block: 11.100.0.0/16
    name: 5region-batch-run-us-west-1
    region: us-west-1
  register: vpcncal

- name: create public subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcncal.vpc.id }}"
    cidr: 11.100.0.0/20
    region: us-west-1
    az: us-west-1a
    map_public: yes
    resource_tags:
      Name: usw1a-public
  register: public_subnet_ncal

- name: create private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcncal.vpc.id }}"
    cidr: 11.100.32.0/19
    region: us-west-1
    az: us-west-1a
    map_public: no
    resource_tags:
      Name: usw1a-private
  register: private_subnet1_ncal

- name: create private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcncal.vpc.id }}"
    cidr: 11.100.64.0/19
    region: us-west-1
    az: us-west-1c
    map_public: no
    resource_tags:
      Name: usw1c-private
  register: private_subnet2_ncal

- name: create Internet GW
  ec2_vpc_igw:
    vpc_id: "{{ vpcncal.vpc.id }}"
    state: present
    region: us-west-1
  register: igw

- name: create nat gateway
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_ncal.subnet.id }}"
    wait: yes
    region: us-west-1
    if_exist_do_not_create: true
  register: nat_gateway

- name: create public route table
  ec2_vpc_route_table:
    state: present
    region: us-west-1
    vpc_id: "{{ vpcncal.vpc.id }}"
    tags:
      Name: Public_RT
    subnets:
      - "{{ public_subnet_ncal.subnet.cidr_block }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_rt

- name: create private route table
  ec2_vpc_route_table:
    state: present
    region: us-west-1
    vpc_id: "{{ vpcncal.vpc.id }}"
    tags:
      Name: Private_RT
    subnets:
      - "{{ private_subnet1_ncal.subnet.cidr_block }}"
      - "{{ private_subnet2_ncal.subnet.cidr_block }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway.nat_gateway_id }}"
  register: private_rt

- name: create vpc endpoint
  ec2_vpc_endpoint:
    state: present
    region: us-west-1
    vpc_id: "{{ vpcncal.vpc.id }}"
    service: com.amazonaws.us-west-1.s3
    route_table_ids:
      - "{{ public_rt.route_table.id }}"
      - "{{ private_rt.route_table.id }}"
  register: vpc_endpoint
